# Audio configurations
TARGET_QCOM_AUDIO_VARIANT := caf-msm8960
TARGET_QCOM_MEDIA_VARIANT := caf-msm8960
BOARD_USES_ALSA_AUDIO := true
AUDIO_USE_LL_AS_PRIMARY_OUTPUT := true
USE_CUSTOM_AUDIO_POLICY := 1
